"""In-code module catalog for help systems."""

MODULE_CATALOG = {
    "packages": "System packages",
    "pypi": "PyPI on remote",
    "docker": "Docker engine/images",
    "docker-compose": "Compose stacks",
    "firewall": "ufw/firewalld",
    "ufw-profiles": "Named firewall profiles",
    "system": "hostname/timezone/services",
    "hostname": "Set hostname",
    "timezone": "Timezone + NTP",
    "swap": "Swap file",
    "users": "Users and groups",
    "ssh": "SSH keys/hardening",
    "ssh-keys-sync": "Sync public keys",
    "sshd-banner": "SSH banner",
    "files": "Files and directories",
    "cron": "Cron jobs",
    "systemd": "Systemd units",
    "limits": "Resource limits",
    "kernel-modules": "Kernel modules",
    "unattended-upgrades": "Auto updates",
    "cleanup": "Disk cleanup",
    "logrotate": "Log rotation",
    "motd": "Message of the day",
    "backup": "Backups",
    "audit": "Security audit",
    "report": "Inventory report",
    "healthcheck": "Health checks",
    "monitoring": "Monitoring tools",
    "certbot": "TLS certificates",
    "nginx": "Nginx sites",
    "caddy": "Caddy server",
    "wireguard": "WireGuard VPN",
    "redis": "Redis",
    "postgres": "PostgreSQL",
    "mysql": "MySQL/MariaDB",
    "nodejs": "Node.js",
    "python-env": "Python venv",
    "git-deploy": "Git deploy",
    "fail2ban-extra": "Extra fail2ban jails",
    "putty-fire": "Protected by Putty-Fire – full hardening",
}
